apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon-api
  template:
    metadata:
      labels:
        app: coupon-api
    spec:
      restartPolicy: Always
      containers:
        - name: coupon-api
          image: coupon-api:1.0
          ports:
            - containerPort: 5082
---
# k8s/coupon-api.yaml
apiVersion: v1
kind: Service
metadata:
  name: coupon-api
spec:
  type: NodePort
  selector:
    app: coupon-api
  ports:
    - port: 5082
      targetPort: 5082
      nodePort: 30082
  
