# k8s/shoppingcart-api.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingcart-api
  template:
    metadata:
      labels:
        app: shoppingcart-api
    spec:
      containers:
        - name: shoppingcart-api
          image: shoppingcart-api:1.0
          ports:
            - containerPort: 5084
          env:
            - name: ServiceUrls__ProductAPI
              value: http://host.docker.internal:30083
            - name: ServiceUrls__CouponAPI
              value: http://host.docker.internal:30082
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingcart-api
spec:
  type: NodePort
  selector:
    app: shoppingcart-api
  ports:
    - port: 5084
      targetPort: 5084
      nodePort: 30084
